In [8]:
from pathlib import Path

import pandas as pd

In [9]:
RESULT_BASES = [Path("results"), Path("code/backend/src/main/python/TEST/results")]

# True: 통합 크롤링(번개장터+중고나라). False: 번개장터 분리 CSV만
USE_INTEGRATED_CSV = True


def collect_glob(pattern):
    paths = []
    for base in RESULT_BASES:
        paths.extend(base.glob(pattern))
    return paths


csv_path = None
if USE_INTEGRATED_CSV:
    for base in RESULT_BASES:
        latest = base / "latest_crawling_no_filter.csv"
        if latest.exists():
            csv_path = latest
            break
    if csv_path is None:
        integrated = collect_glob("통합조회_전체_no_filter_*.csv")
        if integrated:
            csv_path = max(integrated, key=lambda path: path.stat().st_mtime)

if csv_path is None:
    bunjang_only = collect_glob("platform_번개장터_no_filter_*.csv")
    if bunjang_only:
        csv_path = max(bunjang_only, key=lambda path: path.stat().st_mtime)

if csv_path is None:
    raise FileNotFoundError(
        "CSV를 찾을 수 없습니다. results 폴더 또는 USE_INTEGRATED_CSV 설정을 확인하세요."
    )

df = pd.read_csv(csv_path, encoding="utf-8-sig")
print("로드 파일:", csv_path.resolve())
print(df["platform"].value_counts())
df.head()

로드 파일: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\latest_crawling_no_filter.csv
platform
번개장터    18526
중고나라     6781
Name: count, dtype: int64

,keyword,platform,pid,name,price,status,description,image_url,link,date,matched_keywords,canonical_name
0,게이밍 노트북,번개장터,407671617,최저가]ASUS 14인치 게이밍노트북 A14(8845HS/4060/램32,1270000,판매중,NaN,https://media.bunjang.co.kr/product/407671617_...,https://m.bunjang.co.kr/products/407671617,2026-05-12 20:54,게이밍 노트북,게이밍 노트북
1,게이밍 노트북,번개장터,396198529,레노버 LEGION 게이밍 노트북,329000,판매중,NaN,https://media.bunjang.co.kr/product/396198529_...,https://m.bunjang.co.kr/products/396198529,2026-05-12 20:50,게이밍 노트북,게이밍 노트북
2,게이밍 노트북,번개장터,399045782,"MSI i7 고성능 게이밍 노트북(램12GB,1.25TB,신품고가배터리)",529000,판매중,NaN,https://media.bunjang.co.kr/product/399045782_...,https://m.bunjang.co.kr/products/399045782,2026-05-12 20:42,게이밍 노트북,게이밍 노트북
3,게이밍 노트북,번개장터,407667568,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북,3000000,판매중,NaN,https://media.bunjang.co.kr/product/407667568_...,https://m.bunjang.co.kr/products/407667568,2026-05-12 20:34,"갤럭시, 게이밍 노트북",게이밍 노트북
4,게이밍 노트북,번개장터,407666216,[최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32,2150000,판매중,NaN,https://media.bunjang.co.kr/product/407666216_...,https://m.bunjang.co.kr/products/407666216,2026-05-12 20:28,게이밍 노트북,게이밍 노트북

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25307 entries, 0 to 25306
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   keyword           25307 non-null  str
 1   platform          25307 non-null  str
 2   pid               25307 non-null  int64
 3   name              25307 non-null  str
 4   price             25307 non-null  int64
 5   status            25307 non-null  str
 6   description       0 non-null      float64
 7   image_url         25307 non-null  str
 8   link              25307 non-null  str
 9   date              25307 non-null  str
 10  matched_keywords  25307 non-null  str
 11  canonical_name    25307 non-null  str
dtypes: float64(1), int64(2), str(9)
memory usage: 2.3 MB

## 계층 클러스터(L1→L2) · 노트북에서 테스트

[`cluster_by_platform_tokens.run_clustering`](cluster_by_platform_tokens.py) 결과를 **이 노트북만으로** 돌리고 표·요약·트리·텍스트 미리보기까지 확인합니다.

- 저장 위치: **`results/clusters/`** (`token_cluster_*` + `latest_*.csv`).
- **`CLUSTER_PREVIEW_ROWS`**: 숫자 → `df` 앞 N행만 입력(빠른 테스트). **`None`** → 크롤 `csv_path` 전체(시간 소요).
- **`CLUSTER_KWARGS`**: `threshold` / `threshold_l2` 등 실험 파라미터.
- 터미널과 동일한 요약·트리 텍스트는 아래 셀 맨 아래 **텍스트 미리보기**에서 출력합니다. (`CLUSTER_KWARGS`의 `print_stdout_preview=True`로 바꿔도 됩니다.)
- 작업 디렉터리가 프로젝트 루트여도 스크립트가 `TEST` 폴더의 모듈을 자동으로 찾습니다.
- CLI: **`python cluster_by_platform_tokens.py`** 저장 후 터미널 미리보기.

In [11]:
import sys
from pathlib import Path

from IPython.display import Markdown, display

# Jupyter cwd가 프로젝트 루트여도 여기서 모듈을 찾도록 TEST 경로 추가
_here = Path.cwd().resolve()
for _test_root in (_here, _here / "code/backend/src/main/python/TEST"):
    _mod_path = (_test_root / "cluster_by_platform_tokens.py").resolve()
    if _mod_path.is_file():
        if str(_test_root.resolve()) not in sys.path:
            sys.path.insert(0, str(_test_root.resolve()))
        break
else:
    raise FileNotFoundError(
        "cluster_by_platform_tokens.py 를 찾지 못했습니다. "
        "노트북 cwd를 `.../TEST` 또는 프로젝트 루트로 두고 다시 실행하세요."
    )

from cluster_by_platform_tokens import DEFAULT_TOKEN_BLACKLIST_PATH, run_clustering, stdout_preview_clustering

# --- 테스트용 옵션 (여기만 바꿔 실험) ---
# CLUSTER_PREVIEW_ROWS: 숫면 df 앞쪽 N행만 입력 / None 이면 csv_path 통째로 (오래 걸릴 수 있음)
CLUSTER_PREVIEW_ROWS = 800

# run_clustering에 넘기는 인자 — 임계값 실험 시 수정
CLUSTER_KWARGS = dict(
    threshold=0.35,
    min_shared_tokens=1,
    threshold_l2=0.52,
    min_shared_tokens_l2=2,
    run_second_stage=True,
    token_blacklist_path=DEFAULT_TOKEN_BLACKLIST_PATH,
    print_stdout_preview=False,
)

cluster_out_dir = csv_path.resolve().parent / "clusters"
cluster_input = csv_path
preview_note = ""

if CLUSTER_PREVIEW_ROWS is None:
    preview_note = "(전체 행 입력: csv_path)"
else:
    preview_n = min(int(CLUSTER_PREVIEW_ROWS), len(df))
    cluster_input = csv_path.resolve().parent / "_cluster_preview_rows.csv"
    df.head(preview_n).to_csv(cluster_input, index=False, encoding="utf-8-sig")
    preview_note = f"(미리보기: df 상위 {preview_n}행)"

print("클러스터 입력:", cluster_input.resolve(), preview_note)
print("파라미터:", CLUSTER_KWARGS)

cluster_result = run_clustering(
    input_path=cluster_input,
    output_dir=cluster_out_dir,
    **CLUSTER_KWARGS,
)

summ_cols = ["platform", "cluster_l1_id", "cluster_id", "cluster_size", "breadcrumb_names", "derived_product_name", "sample_names"]
tree_cols = ["parent_node_id", "node_id", "platform", "depth", "item_count", "representative_name", "cluster_tokens"]
item_cols = ["platform", "pid", "name", "cluster_l1_id", "cluster_id", "breadcrumb_names", "derived_product_name"]

tree_df_pv = pd.read_csv(cluster_result["latest_tree_path"], encoding="utf-8-sig")
summ_df_pv = pd.read_csv(cluster_result["latest_summary_path"], encoding="utf-8-sig")
items_df_pv = pd.read_csv(cluster_result["latest_item_path"], encoding="utf-8-sig")

print(
    "\n저장:",
    "\n • items:", cluster_result["latest_item_path"],
    "\n • summary:", cluster_result["latest_summary_path"],
    "\n • tree:", cluster_result["latest_tree_path"],
)

display(Markdown("### 검증 요약"))
if summ_df_pv.empty:
    display(Markdown("요약(summary) 행이 없습니다."))
else:
    _vc = summ_df_pv.groupby("platform").size().rename("leaf_l2_clusters").sort_values(ascending=False)
    display(_vc.to_frame())
    display(Markdown(f"행 수: 요약 `{len(summ_df_pv)}` · 트리 `{len(tree_df_pv)}` · 상품 `{len(items_df_pv)}`"))

display(Markdown("### 표: L2 요약 일부"))
summ_show = [c for c in summ_cols if c in summ_df_pv.columns]
tree_show = [c for c in tree_cols if c in tree_df_pv.columns]
item_show = [c for c in item_cols if c in items_df_pv.columns]

if summ_show and not summ_df_pv.empty:
    display(summ_df_pv[summ_show].head(15))
elif not summ_df_pv.empty:
    display(summ_df_pv.head(15))

display(Markdown("### 표: 트리 노드 일부"))

if tree_show and not tree_df_pv.empty:
    display(tree_df_pv.sort_values(["platform", "depth", "node_id"])[tree_show].head(30))
elif not tree_df_pv.empty:
    display(tree_df_pv.head(30))

display(Markdown("### 표: 상품 랜덤 표본"))

if len(items_df_pv):
    sampled = items_df_pv[item_show] if item_show else items_df_pv
    n = min(12, len(sampled))
    part = sampled.sample(n, random_state=0)
    sort_keys = [k for k in ["platform", "cluster_id"] if k in part.columns]
    display(part.sort_values(sort_keys) if sort_keys else part)
else:
    display(items_df_pv)

display(Markdown("### 텍스트 미리보기 (모듈 `stdout_preview_clustering`)"))
print(
    stdout_preview_clustering(summ_df_pv, tree_df_pv, max_summary_rows=12, max_tree_rows=26)
)

클러스터 입력: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\_cluster_preview_rows.csv (미리보기: df 상위 800행)
파라미터: {'threshold': 0.35, 'min_shared_tokens': 1, 'threshold_l2': 0.52, 'min_shared_tokens_l2': 2, 'run_second_stage': True, 'token_blacklist_path': WindowsPath('C:/project/kdtproject/kdtproject/code/backend/src/main/python/TEST/blacklist_tokens.csv'), 'print_stdout_preview': False}
입력 파일: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\_cluster_preview_rows.csv
상품별 클러스터 결과: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\token_cluster_items_20260517_1616.csv
클러스터 요약 결과: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\token_cluster_summary_20260517_1616.csv
트리 노드 결과: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\token_cluster_tree_20260517_1616.csv

플랫폼별 최종 클러스터(L2 리프) 수
platform
번개장터    320
중고나라    221
Name: cluster_id, dtype: int64

저장:
 • items: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\latest_token_cluster_items.csv
 • summary: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\latest_token_cluster_summary.csv
 • tree: C:\project\kdtproject\kdtproject\code\backend\src\main\python\TEST\results\clusters\latest_token_cluster_tree.csv

### 검증 요약

          leaf_l2_clusters
platform
번개장터                   320
중고나라                   221

행 수: 요약 `541` · 트리 `790` · 상품 `800`

### 표: L2 요약 일부

,platform,cluster_l1_id,cluster_id,cluster_size,breadcrumb_names,derived_product_name,sample_names
0,번개장터,번개장터_002,번개장터_002_s01,82,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP ...,HP OMEN 16 게이밍 노트북 RTX 5070 화이트!! 가격다운급매,레노버 LEGION 게이밍 노트북 | 에이수스TUF 게이밍 노트북 | i7 게이밍 ...
1,번개장터,번개장터_037,번개장터_037_s01,11,14.5인치 3D 노트북/ssd 탑재/외장그래픽,14.5인치 3D 노트북/ssd 탑재/외장그래픽,14.5인치 3D 노트북/ssd 탑재/외장그래픽
2,번개장터,번개장터_004,번개장터_004_s02,7,[최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32 › 최저가...,최저가]HP 16인치 게이밍노트북 오멘슬림(i7-14th/4060/1TB,[최저가]HP 16인치 게이밍노트북 오멘(i5-13/4060/QHD) | 최저가]H...
3,번개장터,번개장터_003,번개장터_003_s01,6,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북
4,번개장터,번개장터_013,번개장터_013_s01,6,[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB),[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB),[최저가]MSI 17인치 게이밍노트북 브라보(7735HS/4060) | [최저가]M...
5,번개장터,번개장터_002,번개장터_002_s15,5,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP ...,HP 오멘 16 게이밍 노트북 (RTX / 240Hz / 라이젠7),"RTX4060 HP 오멘 게이밍 노트북(울트라7,14인치,2.8k) | Hp 빅터스..."
6,번개장터,번개장터_019,번개장터_019_s01,5,최저가]에이서 16인치 게이밍노트북 헬리오스 네오(i5-13th/4060 › 최저가...,최저가]에이서 16인치 게이밍노트북 헬리오스(275HX/5070/풀업글),최저가]에이서 16인치 게이밍노트북 헬리오스(275HX/5070/풀업글) | [최저...
7,번개장터,번개장터_002,번개장터_002_s29,4,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › LG ...,LG 15인치 울트라PC i7 외장 게이밍 노트북,LG 게이밍 노트북 i7-4세대 | 게이밍 노트북 LG 15U780(i7-8550...
8,번개장터,번개장터_002,번개장터_002_s132,4,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › LG ...,LG 게이밍 노트북 i5-8250U 모델입니다. GTX 1050 그래픽,LG 게이밍 노트북 i7 / GTX 1050 | 게이밍 LG 노트북 i5-8250U...
9,번개장터,번개장터_002,번개장터_002_s03,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › MSI...,MSI 펄스 17 RTX4070 게이밍 노트북 30일사용,MSI 게이밍 노트북 펄스 17 rtx4070 | MSI 펄스 17 RTX4070 ...
10,번개장터,번개장터_002,번개장터_002_s17,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 게이밍...,게이밍노트북 ASUS ROG Strix G17 RTX3060 게이밍,게이밍노트북 ASUS ROG Strix G17 RTX3060 게이밍 | ASUS R...
11,번개장터,번개장터_002,번개장터_002_s18,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 삼성 ...,삼성 오디세이 게이밍 노트북 i7 8세대 gtx 1060 엑셀한글 캐드,삼성 오디세이 게이밍 노트북 i7 8세대 gtx 1060 엑셀한글 캐드 | 삼성 오...
12,번개장터,번개장터_002,번개장터_002_s19,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › MSI...,"MSI 게이밍 노트북 블랙 GF65 thin, RTX3060","MSI 게이밍 노트북 블랙 GF65 thin, RTX3060 | MSI 게이밍 노트..."
13,번개장터,번개장터_002,번개장터_002_s25,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › Del...,Dell 델 G5 5590 i7 9세대 GTX1650 게이밍 노트북,델 XPS 게이밍 노트북 i7 GTX960 | Dell 델 G5 5590 i7 9세...
14,번개장터,번개장터_002,번개장터_002_s42,3,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 아수스...,아수스 ROG 게이밍 노트북 / 17인치 / GTX 1060,아수스 ROG 게이밍 노트북 / 17인치 / GTX 1060 | 게이밍 노트북 GT...

### 표: 트리 노드 일부

,parent_node_id,node_id,platform,depth,item_count,representative_name,cluster_tokens
0,NaN,번개장터::__root,번개장터,0,480,NaN,NaN
1,번개장터::__root,번개장터_001,번개장터,1,1,최저가]ASUS 14인치 게이밍노트북 A14(8845HS/4060/램32,최저가]asus 14인치 게이밍노트북 a14(8845hs/4060/램32
2,번개장터::__root,번개장터_002,번개장터,1,269,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북,게이밍 노트북 hp asus msi i7 레노버 rog 삼성 omen 아수스 16 ...
3,번개장터::__root,번개장터_003,번개장터,1,6,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북,매입]미개봉 lg그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북
4,번개장터::__root,번개장터_004,번개장터,1,11,[최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32,게이밍노트북 최저가]hp 16인치 오멘(라이젠9 17인치 365/5070/램32 오...
5,번개장터::__root,번개장터_005,번개장터,1,4,MSI GF63 게이밍노트북 RTX2050/인텔i5/램32GB/윈11프로,msi 게이밍노트북 부품용으로 가져가세요 gf63 rtx2050/인텔i5/램32gb...
6,번개장터::__root,번개장터_006,번개장터,1,1,"msi사이보그 게이밍 노트북 rtx5060, ddr5 16b, 144hz",msi사이보그 게이밍 노트북 rtx5060 ddr5 16b 144hz
7,번개장터::__root,번개장터_007,번개장터,1,2,[무상남음 S급 ] MSI 게이밍노트북 i7 32G RTX4060 1TB,msi 게이밍노트북 i7 rtx4060 풀박 ddr5 144hz 무상남음 s급 32...
8,번개장터::__root,번개장터_008,번개장터,1,3,최저가]기가바이트 16인치 게이밍노트북 어로스(i7-14/4070/1TB,최저가]기가바이트 16인치 게이밍노트북 어로스(i7-14/4070/1tb 에어로(3...
9,번개장터::__root,번개장터_009,번개장터,1,1,[매입]갤럭시북프로 360 맥북 PC 게이밍노트북 24시간 출장방문매입,매입]갤럭시북프로 360 맥북 pc 게이밍노트북 24시간 출장방문매입
10,번개장터::__root,번개장터_010,번개장터,1,2,S급 MSI 레이더 게이밍 노트북 울트라9 64램 RTX5080 4T,s급 msi 레이더 게이밍 노트북 울트라9 64램 rtx5080 4t
11,번개장터::__root,번개장터_011,번개장터,1,1,[매입]ASUS 델 그램 게이밍노트북 미개봉 중고 기업용 대량 출장매입,매입]asus 델 그램 게이밍노트북 미개봉 중고 기업용 대량 출장매입
12,번개장터::__root,번개장터_012,번개장터,1,1,[매입]게이밍노트북 맥북프로 맥북에어 M4 M3 미개봉최고가매입,매입]게이밍노트북 맥북프로 맥북에어 m4 m3 미개봉최고가매입
13,번개장터::__root,번개장터_013,번개장터,1,7,[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB),최저가]msi 17인치 게이밍노트북 알파(7945hx/4070/1tb 브라보(773...
14,번개장터::__root,번개장터_014,번개장터,1,1,주연테크 L8CS36 리오나인 17.3인치 게이밍노트북,주연테크 l8cs36 리오나인 17.3인치 게이밍노트북
15,번개장터::__root,번개장터_015,번개장터,1,1,[단순개봉]ASUS 비보북 V16 RTX4050 게이밍노트북 판매,단순개봉]asus 비보북 v16 rtx4050 게이밍노트북 판매
16,번개장터::__root,번개장터_016,번개장터,1,1,GIGABYTE AORUS 16X ASG-53KR게이밍노트북,gigabyte aorus 16x asg-53kr게이밍노트북
17,번개장터::__root,번개장터_017,번개장터,1,1,GTX950!!>MSI15인치게이밍노트북,gtx950!!>msi15인치게이밍노트북
18,번개장터::__root,번개장터_018,번개장터,1,1,삼성 게이밍노트북 15인치 i7 / 32g / 512g / 2060,삼성 게이밍노트북 15인치 i7 32g 512g 2060
19,번개장터::__root,번개장터_019,번개장터,1,6,최저가]에이서 16인치 게이밍노트북 헬리오스 네오(i5-13th/4060,최저가]에이서 16인치 게이밍노트북 헬리오스(275hx/5070/풀업글 헬리오스 네...
20,번개장터::__root,번개장터_020,번개장터,1,2,한성 게이밍노트북 RTX3060 / 32GB / 512GB,한성 게이밍노트북 rtx3060 32gb 512gb 1테라
21,번개장터::__root,번개장터_021,번개장터,1,1,롤피파가능!!>i5사양 에이서15인치게이밍노트북,롤피파가능!!>i5사양 에이서15인치게이밍노트북
22,번개장터::__root,번개장터_022,번개장터,1,1,[사은품+무료배송]게이밍 PC 철제 노트북 컴퓨터 데스크탑 테이블 책상,사은품 플러스 무료배송]게이밍 pc 철제 노트북 컴퓨터 데스크탑 테이블 책상
23,번개장터::__root,번개장터_023,번개장터,1,1,ASUS ROG Zephyrus G15 GA502IV-AZ087,asus rog zephyrus g15 ga502iv-az087
24,번개장터::__root,번개장터_024,번개장터,1,1,Rog flow z13 2025 풀박스,rog flow z13 2025 풀박스
25,번개장터::__root,번개장터_025,번개장터,1,1,Asus rog z13 rtx4060 태블릿 가벼운 고사양 노트북,asus rog z13 rtx4060 태블릿 가벼운 고사양 노트북
26,번개장터::__root,번개장터_026,번개장터,1,1,asus 2025 비보북 16인치 고사양 사무용 게이밍 중고노트북,asus 2025 비보북 16인치 고사양 사무용 게이밍 중고노트북
27,번개장터::__root,번개장터_027,번개장터,1,1,델 DELL 2025 PRO 14 초경량 고성능 노트북,델 dell 2025 프로 14 초경량 고성능 노트북
28,번개장터::__root,번개장터_028,번개장터,1,1,RTX4060 아수스 비보북 게이밍 노트북(120hz),rtx4060 아수스 비보북 게이밍 노트북(120hz
29,번개장터::__root,번개장터_029,번개장터,1,1,아수스 i7-10870H 16G GTX1650Ti 게이밍노트북 팝니다,아수스 i7-10870h 16g gtx1650ti 게이밍노트북 팝니다

### 표: 상품 랜덤 표본

,platform,pid,name,cluster_l1_id,cluster_id,breadcrumb_names,derived_product_name
40,번개장터,407356200,Msi 게이밍 노트북 17인치 팝니다 .롤.서든.피파.옵치.포토샵.캐드,번개장터_002,번개장터_002_s01,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP ...,HP OMEN 16 게이밍 노트북 RTX 5070 화이트!! 가격다운급매
14,번개장터,406327594,MSI 17인치 게이밍 노트북 4060,번개장터_002,번개장터_002_s01,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP ...,HP OMEN 16 게이밍 노트북 RTX 5070 화이트!! 가격다운급매
231,번개장터,237701928,(일산) msi 게이밍 노트북 15인치 지포스,번개장터_002,번개장터_002_s120,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › (일산...,(일산) msi 게이밍 노트북 15인치 지포스
236,번개장터,394539076,ASUS 게이밍 노트북 / RTX5060 / RAM 32GB / S급,번개장터_002,번개장터_002_s125,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › ASU...,ASUS 게이밍 노트북 / RTX5060 / RAM 32GB / S급
240,번개장터,387745500,게이밍 노트북ASUS ROG Strix G15 G512LV,번개장터_002,번개장터_002_s129,HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 게이밍...,게이밍 노트북ASUS ROG Strix G15 G512LV
299,번개장터,404407303,S급 MSI 레이더 게이밍 노트북 울트라9 64램 RTX5080 4T,번개장터_010,번개장터_010_s01,S급 MSI 레이더 게이밍 노트북 울트라9 64램 RTX5080 4T,S급 MSI 레이더 게이밍 노트북 울트라9 64램 RTX5080 4T
303,번개장터,407636713,[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB),번개장터_013,번개장터_013_s01,[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB),[최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB)
389,번개장터,405620294,MSI 게이밍 노트북 A10 R9 m290x 신품배터리 GX60 3CC,번개장터_067,번개장터_067_s01,MSI 게이밍 노트북 A10 R9 m290x 신품배터리 GX60 3CC,MSI 게이밍 노트북 A10 R9 m290x 신품배터리 GX60 3CC
436,번개장터,406500169,369번 아수스 14인치 그래픽작업용 게이밍 중고노트북,번개장터_104,번개장터_104_s01,369번 아수스 14인치 그래픽작업용 게이밍 중고노트북,369번 아수스 14인치 그래픽작업용 게이밍 중고노트북
500,중고나라,227832236,게이밍 노트북,중고나라_004,중고나라_004_s05,HP 오멘 맥스 16 RTX 5070 ti 신형 게이밍 노트북 작업용 초고성능 OM...,MSI Sword GF76 B13VFK 게이밍 노트북 팝니다
495,중고나라,141909471,아수스 게이밍 노트북 fx503v 판매,중고나라_004,중고나라_004_s05,HP 오멘 맥스 16 RTX 5070 ti 신형 게이밍 노트북 작업용 초고성능 OM...,MSI Sword GF76 B13VFK 게이밍 노트북 팝니다
605,중고나라,228475044,HP 2025 오멘 16 라이젠 350 rtx5060 게이밍 노트북,중고나라_004,중고나라_004_s71,HP 오멘 맥스 16 RTX 5070 ti 신형 게이밍 노트북 작업용 초고성능 OM...,HP 2025 오멘 16 라이젠 350 rtx5060 게이밍 노트북

### 텍스트 미리보기 (모듈 `stdout_preview_clustering`)

[L2 리프 요약 · 상위 12 행]
platform    cluster_id  cluster_size                                                       breadcrumb_preview                     derived_product_name                                                           sample_preview
    번개장터  번개장터_002_s01            82 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP OMEN 16 게이밍 노트북 RTX 5070 화 HP OMEN 16 게이밍 노트북 RTX 5070 화이트!! 가격다운급매 레노버 LEGION 게이밍 노트북 | 에이수스TUF 게이밍 노트북 | i7 게이밍 1660ti 노트북 | ASUS ROG 게이밍
    번개장터  번개장터_037_s01            11                                               14.5인치 3D 노트북/ssd 탑재/외장그래픽               14.5인치 3D 노트북/ssd 탑재/외장그래픽                                               14.5인치 3D 노트북/ssd 탑재/외장그래픽
    번개장터  번개장터_004_s02             7 [최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32 › 최저가]HP 16인치 게이밍노트북 오멘슬림(i7-14 최저가]HP 16인치 게이밍노트북 오멘슬림(i7-14th/4060/1TB [최저가]HP 16인치 게이밍노트북 오멘(i5-13/4060/QHD) | 최저가]HP 16인치 게이밍노트북 오멘슬림(i7-14th
    번개장터  번개장터_003_s01             6                                    [매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북    [매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북                                    [매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북
    번개장터  번개장터_013_s01             6                                 [최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB) [최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB) [최저가]MSI 17인치 게이밍노트북 브라보(7735HS/4060) | [최저가]MSI 17인치 게이밍노트북 알파(7945HX/4
    번개장터  번개장터_002_s15             5 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › HP 오멘 16 게이밍 노트북 (RTX / 240Hz    HP 오멘 16 게이밍 노트북 (RTX / 240Hz / 라이젠7) RTX4060 HP 오멘 게이밍 노트북(울트라7,14인치,2.8k) | Hp 빅터스 16 게이밍 노트북 판매합니다 RTX4060
    번개장터  번개장터_019_s01             5 최저가]에이서 16인치 게이밍노트북 헬리오스 네오(i5-13th/4060 › 최저가]에이서 16인치 게이밍노트북 헬리오스(275H 최저가]에이서 16인치 게이밍노트북 헬리오스(275HX/5070/풀업글) 최저가]에이서 16인치 게이밍노트북 헬리오스(275HX/5070/풀업글) | [최저가]에이서 16인치 게이밍노트북 헬리오스(i5-
    번개장터  번개장터_002_s29             4   HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › LG 15인치 울트라PC i7 외장 게이밍 노트북              LG 15인치 울트라PC i7 외장 게이밍 노트북 LG 게이밍 노트북 i7-4세대 | 게이밍 노트북  LG 15U780(i7-8550U/GTX1050) 노트북 | LG 울트라PC
    번개장터 번개장터_002_s132             4 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › LG 게이밍 노트북 i5-8250U 모델입니다. GT  LG 게이밍 노트북 i5-8250U 모델입니다. GTX 1050 그래픽 LG 게이밍 노트북 i7 / GTX 1050 | 게이밍 LG 노트북 i5-8250U GTX 1050 256GB SSD | LG 게
    번개장터  번개장터_002_s03             3 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › MSI 펄스 17 RTX4070 게이밍 노트북 30일          MSI 펄스 17 RTX4070 게이밍 노트북 30일사용 MSI 게이밍 노트북 펄스 17 rtx4070 | MSI 펄스 17 RTX4070 게이밍 노트북 30일사용 | MSI 스워드 17
    번개장터  번개장터_002_s17             3 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 게이밍노트북 ASUS ROG Strix G17 RTX    게이밍노트북 ASUS ROG Strix G17 RTX3060 게이밍 게이밍노트북 ASUS ROG Strix G17 RTX3060 게이밍 | ASUS ROG STRIX 게이밍노트북 / 17인치 / R
    번개장터  번개장터_002_s18             3 HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북 › 삼성 오디세이 게이밍 노트북 i7 8세대 gtx 10  삼성 오디세이 게이밍 노트북 i7 8세대 gtx 1060 엑셀한글 캐드 삼성 오디세이 게이밍 노트북 i7 8세대 gtx 1060 엑셀한글 캐드 | 삼성 오디세이 게이밍 노트북 i5 GTX1060 캐드

[트리 노드 · 깊이·노드ID 미리보기]
(0) 번개장터::__root  n=480  nan
  (1) 번개장터_001  n=1  최저가]ASUS 14인치 게이밍노트북 A14(8845HS/4060/램32
  (1) 번개장터_002  n=269  HP 오멘 MAX 16 울트라9 RTX5080 램 64기가 게이밍 노트북
  (1) 번개장터_003  n=6  [매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북
  (1) 번개장터_004  n=11  [최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32
  (1) 번개장터_005  n=4  MSI GF63 게이밍노트북 RTX2050/인텔i5/램32GB/윈11프로
  (1) 번개장터_006  n=1  msi사이보그 게이밍 노트북 rtx5060, ddr5 16b, 144hz
  (1) 번개장터_007  n=2  [무상남음 S급 ] MSI 게이밍노트북 i7 32G RTX4060 1TB
  (1) 번개장터_008  n=3  최저가]기가바이트 16인치 게이밍노트북 어로스(i7-14/4070/1TB
  (1) 번개장터_009  n=1  [매입]갤럭시북프로 360 맥북 PC 게이밍노트북 24시간 출장방문매입
  (1) 번개장터_010  n=2  S급 MSI 레이더 게이밍 노트북 울트라9 64램 RTX5080 4T
  (1) 번개장터_011  n=1  [매입]ASUS 델 그램 게이밍노트북 미개봉 중고 기업용 대량 출장매입
  (1) 번개장터_012  n=1  [매입]게이밍노트북 맥북프로 맥북에어 M4 M3 미개봉최고가매입
  (1) 번개장터_013  n=7  [최저가]MSI 17인치 게이밍노트북 알파(7945HX/4070/1TB)
  (1) 번개장터_014  n=1  주연테크 L8CS36 리오나인 17.3인치 게이밍노트북
  (1) 번개장터_015  n=1  [단순개봉]ASUS 비보북 V16 RTX4050  게이밍노트북 판매
  (1) 번개장터_016  n=1  GIGABYTE AORUS 16X ASG-53KR게이밍노트북
  (1) 번개장터_017  n=1  GTX950!!>MSI15인치게이밍노트북
  (1) 번개장터_018  n=1  삼성 게이밍노트북 15인치  i7 / 32g / 512g / 2060
  (1) 번개장터_019  n=6  최저가]에이서 16인치 게이밍노트북 헬리오스 네오(i5-13th/4060
  (1) 번개장터_020  n=2  한성 게이밍노트북 RTX3060 / 32GB / 512GB
  (1) 번개장터_021  n=1  롤피파가능!!>i5사양 에이서15인치게이밍노트북
  (1) 번개장터_022  n=1  [사은품+무료배송]게이밍 PC 철제 노트북 컴퓨터 데스크탑 테이블 책상
  (1) 번개장터_023  n=1  ASUS ROG Zephyrus G15 GA502IV-AZ087
  (1) 번개장터_024  n=1  Rog flow z13 2025 풀박스
  (1) 번개장터_025  n=1  Asus rog z13 rtx4060 태블릿 가벼운 고사양 노트북

… 외 764개 노드 (CSV 참고)

### 저장된 클러스터 결과만 다시 불러오기

`run_clustering`을 다시 돌리지 않고 **`results/clusters/latest_token_cluster_*.csv`** 만 읽습니다.  
성공 시 위와 동일하게 `summ_df_pv`, `tree_df_pv`, `items_df_pv` 변수가 채워져 이후 탐색에 쓸 수 있습니다.

In [ ]:
from IPython.display import Markdown, display

CLUSTER_RELOAD_BASE = csv_path.resolve().parent / "clusters"
_reload_paths = {
    "summary": CLUSTER_RELOAD_BASE / "latest_token_cluster_summary.csv",
    "tree": CLUSTER_RELOAD_BASE / "latest_token_cluster_tree.csv",
    "items": CLUSTER_RELOAD_BASE / "latest_token_cluster_items.csv",
}

missing = []
for label, path in _reload_paths.items():
    ok = path.is_file()
    print(f"[{'OK' if ok else '없음'}] {label:8s}", path.resolve())
    if not ok:
        missing.append(label)

if not missing:
    summ_df_pv = pd.read_csv(_reload_paths["summary"], encoding="utf-8-sig")
    tree_df_pv = pd.read_csv(_reload_paths["tree"], encoding="utf-8-sig")
    items_df_pv = pd.read_csv(_reload_paths["items"], encoding="utf-8-sig")
    display(
        Markdown(
            "재로드 완료: **`summ_df_pv`**, **`tree_df_pv`**, **`items_df_pv`** (클러스터 테스트 셀과 동일 이름)"
        )
    )
    display(summ_df_pv.head(8))
else:
    display(
        Markdown(
            "위 **클러스터 테스트** 셀을 먼저 실행하거나, `results/clusters/`에 `latest_*.csv`가 있는지 확인하세요."
        )
    )

In [4]:
base_cols = ["keyword", "platform", "pid", "name", "price", "matched_keywords"]

missing = [c for c in base_cols if c not in df.columns]
if missing:
    raise ValueError(f"필요한 컬럼이 없습니다: {missing}")


def tokenize_by_space(text):
    """name을 공백(연속 공백 포함) 기준으로 분리합니다."""
    if pd.isna(text):
        return []
    return [tok for tok in str(text).split() if tok]


token_df = df[base_cols].copy()
token_df["name_tokens"] = token_df["name"].apply(tokenize_by_space)
token_df["token_count"] = token_df["name_tokens"].str.len()
token_df.head(10)

,keyword,platform,pid,name,price,matched_keywords,name_tokens,token_count
0,게이밍 노트북,번개장터,407671617,최저가]ASUS 14인치 게이밍노트북 A14(8845HS/4060/램32,1270000,게이밍 노트북,"[최저가]ASUS, 14인치, 게이밍노트북, A14(8845HS/4060/램32]",4
1,게이밍 노트북,번개장터,396198529,레노버 LEGION 게이밍 노트북,329000,게이밍 노트북,"[레노버, LEGION, 게이밍, 노트북]",4
2,게이밍 노트북,번개장터,399045782,"MSI i7 고성능 게이밍 노트북(램12GB,1.25TB,신품고가배터리)",529000,게이밍 노트북,"[MSI, i7, 고성능, 게이밍, 노트북(램12GB,1.25TB,신품고가배터리)]",5
3,게이밍 노트북,번개장터,407667568,[매입]미개봉 LG그램 갤럭시북 맥북 기업용 대량매입 게이밍 노트북,3000000,"갤럭시, 게이밍 노트북","[[매입]미개봉, LG그램, 갤럭시북, 맥북, 기업용, 대량매입, 게이밍, 노트북]",8
4,게이밍 노트북,번개장터,407666216,[최저가]HP 16인치 게이밍노트북 오멘(라이젠9 365/5070/램32,2150000,게이밍 노트북,"[[최저가]HP, 16인치, 게이밍노트북, 오멘(라이젠9, 365/5070/램32]",5
5,게이밍 노트북,번개장터,406964298,에이수스TUF 게이밍 노트북,640000,게이밍 노트북,"[에이수스TUF, 게이밍, 노트북]",3
6,게이밍 노트북,번개장터,407664491,MSI 게이밍 노트북 펄스 17 rtx4070,1200000,게이밍 노트북,"[MSI, 게이밍, 노트북, 펄스, 17, rtx4070]",6
7,게이밍 노트북,번개장터,398590249,msi 게이밍노트북 부품용으로 가져가세요^^!!,200000,게이밍 노트북,"[msi, 게이밍노트북, 부품용으로, 가져가세요^^!!]",4
8,게이밍 노트북,번개장터,407661175,[최저가]HP 16인치 게이밍노트북 오멘(i5-13/4060/QHD),1090000,게이밍 노트북,"[[최저가]HP, 16인치, 게이밍노트북, 오멘(i5-13/4060/QHD)]",4
9,게이밍 노트북,번개장터,407611942,HP Victus 게이밍 노트북 i5 RTX3050ti,750000,게이밍 노트북,"[HP, Victus, 게이밍, 노트북, i5, RTX3050ti]",6

In [5]:
TOP_N = 50

long_tokens = token_df.explode("name_tokens").rename(columns={"name_tokens": "token"})
long_tokens = long_tokens.dropna(subset=["token"])

occurrence_counts = long_tokens.groupby("token").size().rename("occurrence_count")
product_counts = long_tokens.drop_duplicates(subset=["pid", "token"]).groupby("token").size().rename("product_count")

freq_df = pd.concat([occurrence_counts, product_counts], axis=1).sort_values(
    "occurrence_count", ascending=False
)
freq_df.head(TOP_N)

       occurrence_count  product_count
token
갤럭시                4227           4222
중고폰                1811           1797
무잔상                1582           1582
핫토이                1562           1560
세이코                1386           1383
블랙                 1285           1285
스텔라이브              1250           1250
삼성                 1072           1072
정상공기기              1047           1047
만년필                 938            924
바이씨니                903            899
판매합니다               864            864
팝니다                 840            837
미개봉                 772            767
256GB               768            768
판매                  734            731
게이밍                 635            635
256G                619            619
PS5                 617            617
/                   616            436
노트북                 603            596
메탈빌드                586            583
화이트                 584            584
시계                  537            529
빈티지                 517            514
던스트                 507            507
제라늄                 506            506
피규어                 499            498
던스                  493            492
A급                  489            489
256기가               464            464
케이스                 454            447
공기계                 429            429
새상품                 409            409
안스리움                381            380
블루                  372            357
ps5                 368            367
128GB               364            364
골드바                 362            359
울트라                 353            351
부산중고폰               341            341
아크릴                 325            324
당일발송                322            322
붉은사막                321            320
S급                  312            312
팝니다.                308            308
+                   296            270
울산중고폰               294            294
제작                  287            286
256                 272            272

In [6]:
TOP_PER_PLATFORM = 20

occ_by_platform = (
    long_tokens.groupby(["platform", "token"])
    .size()
    .rename("occurrence_count")
    .reset_index()
)

product_by_platform = (
    long_tokens.drop_duplicates(subset=["platform", "pid", "token"])
    .groupby(["platform", "token"])
    .size()
    .rename("product_count")
    .reset_index()
)

freq_by_platform = occ_by_platform.merge(product_by_platform, on=["platform", "token"])
freq_by_platform = freq_by_platform.sort_values(
    ["platform", "occurrence_count"], ascending=[True, False]
)

# 플랫폼별 전체 빈도표: freq_by_platform_for["번개장터"].head(30)
freq_by_platform_for = {
    plat: group.reset_index(drop=True)
    for plat, group in freq_by_platform.groupby("platform", sort=True)
}

# 조회 조건 (기본: 플랫폼별 상위 TOP_PER_PLATFORM 토큰 미리보기)
QUERY_PLATFORM = None  # 예: "번개장터", "중고나라"
TOKEN_CONTAINS = None  # 예: "갤럭시"

if QUERY_PLATFORM is None and TOKEN_CONTAINS is None:
    platform_token_preview = freq_by_platform.groupby("platform", group_keys=False).head(
        TOP_PER_PLATFORM
    )
else:
    q = freq_by_platform
    if QUERY_PLATFORM is not None:
        q = q.loc[q["platform"] == QUERY_PLATFORM]
    if TOKEN_CONTAINS:
        q = q.loc[q["token"].astype(str).str.contains(TOKEN_CONTAINS, regex=False, na=False)]
    platform_token_preview = q.head(TOP_PER_PLATFORM)

if platform_token_preview.empty:
    print("조회 결과가 비어 있습니다.")
    print("- CSV에 해당 플랫폼/토큰이 없거나, 위 셀(token_df/long_tokens)을 먼저 실행했는지 확인하세요.")
    if "df" in dir() and hasattr(df, "columns") and "platform" in df.columns:
        print("- 현재 df의 platform:", df["platform"].dropna().unique().tolist())
    print("- freq_by_platform_for 키:", list(freq_by_platform_for.keys()))

platform_token_preview

      platform  token  occurrence_count  product_count
7538      번개장터    갤럭시              4032           4027
16325     번개장터    중고폰              1771           1757
11053     번개장터    무잔상              1549           1549
18986     번개장터    핫토이              1156           1155
12089     번개장터     블랙              1155           1155
15959     번개장터  정상공기기              1047           1047
13389     번개장터  스텔라이브              1036           1036
12808     번개장터    세이코              1015           1013
12477     번개장터     삼성               984            984
2167      번개장터  256GB               714            714
18015     번개장터  판매합니다               641            641
18092     번개장터    팝니다               587            585
2163      번개장터   256G               571            571
19201     번개장터    화이트               527            527
1222      번개장터      /               512            369
11372     번개장터   바이씨니               509            507
9461      번개장터    던스트               507            507
17970     번개장터     판매               499            498
10627     번개장터    만년필               493            486
3730      번개장터     A급               477            477
24675     중고나라   메탈빌드               455            453
24556     중고나라    만년필               445            438
23765     중고나라     던스               434            433
29156     중고나라    핫토이               406            405
24994     중고나라   바이씨니               394            392
26531     중고나라   안스리움               379            378
25802     중고나라    세이코               371            370
22978     중고나라    게이밍               318            318
27486     중고나라    제라늄               318            318
24815     중고나라    미개봉               305            300
25368     중고나라   붉은사막               297            296
21509     중고나라    PS5               286            286
23533     중고나라    노트북               279            275
28623     중고나라    팝니다               253            252
22419     중고나라    ps5               242            241
28568     중고나라     판매               235            233
28582     중고나라  판매합니다               223            223
26114     중고나라  스텔라이브               214            214
23067     중고나라    골드바               202            201
22810     중고나라    갤럭시               195            195

In [7]:
JOONGNA = "중고나라"

if JOONGNA in freq_by_platform_for:
    freq_by_platform_for[JOONGNA].head(TOP_PER_PLATFORM)
else:
    print(f"'{JOONGNA}' 행이 없습니다. Cell 1에서 통합 CSV를 읽거나, 아래 중 실제 있는 플랫폼을 쓰세요.")
    print(list(freq_by_platform_for.keys()))